import thumb1 from "../assets/Images/thumb1.webp"
import thumb2 from "../assets/Images/thumb2.webp"
import thumb3 from "../assets/Images/thumb3.webp"
import thumb4 from "../assets/Images/thumb4.webp"
import thumb5 from "../assets/Images/thumb5.webp"
import thumb6 from "../assets/Images/thumb6.webp"
import thumb7 from "../assets/Images/thumb7.webp"
import thumb8 from "../assets/Images/thumb8.webp"
import thumb9 from "../assets/Images/thumb9.webp"
import thumb10 from "../assets/Images/thumb10.webp"
import thumb11 from "../assets/Images/thumb11.webp"
import thumb12 from "../assets/Images/thumb12.webp"
import img1 from "../assets/Images/img1.webp"
import img2 from "../assets/Images/img2.webp"
import img3 from "../assets/Images/img3.webp"
import img4 from "../assets/Images/img4.webp"
import img5 from "../assets/Images/img5.webp"
import img6 from "../assets/Images/img6.webp"
import img7 from "../assets/Images/img7.webp"
import img8 from "../assets/Images/img8.webp"
import img9 from "../assets/Images/img9.webp"
import img10 from "../assets/Images/img10.webp"
import img11 from "../assets/Images/img11.webp"
import img12 from "../assets/Images/img12.webp"

export const images = [
  {'img': img1, 'thumb': thumb1},
  {'img': img2, 'thumb': thumb2},
  {'img': img3, 'thumb': thumb3},
  {'img': img4, 'thumb': thumb4},
  {'img': img5, 'thumb': thumb5},
  {'img': img6, 'thumb': thumb6},
  {'img': img7, 'thumb': thumb7},
  {'img': img8, 'thumb': thumb8},
  {'img': img9, 'thumb': thumb9},
  {'img': img10, 'thumb': thumb10},
  {'img': img11, 'thumb': thumb11},
  {'img': img12, 'thumb': thumb12},
]